DDGameProtocol ::= IMPLICIT TAGS 
BEGIN

-------------------
--COMMAND SECTION--
-------------------


--Update physics of ship state
Update :== [APPLICATION 5] SEQUENCE {
    seqNum	    INTEGER,
    source      PeerGID,
    shipData    SEQUENCE OF ShipData;
}

----------------
--DATA SECTION--
----------------

--Contains name of peer and peer GID
PeerData :== SEQUENCE {
	name PlayerName,
	gid  PeerGID;
}

PlayerName :== UTF8String;
PeerGID :== UTF8String;

ShipData :== SEQUENCE {
	lastUpdate		INTEGER,
    player  		PeerData,
    xDestination   	INTEGER,
    yDestination  	INTEGER;
}

END